[package]
name = "frontend"
version = "0.1.0"
authors = ["inanna malick <inanna@recursion.wtf>"]
edition = "2018"

[dependencies]
embed-wasm = "0.1.1"
phf = "0.8.0"

[build-dependencies]
embed-wasm-build = "0.1.1"
